name: Deploy To S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout v2
        uses: actions/checkout@v2

      - name: Setup .env for CRA
        run: |
          echo "REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }}" >> .env 
          echo "REACT_APP_SOCKET_SERVER_URL=${{ secrets.REACT_APP_SOCKET_SERVER_URL }}" >> .env

      - name: Install Dependencies
        run: npm install
        env:
          CI: false

      - name: Build app
        run: npm run build

      - name: Deploy To S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build/ s3://wear-frontend
